# Generated by Django 4.2.24 on 2025-09-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('it', 'Information Technology'), ('administration', 'Administration'), ('human_resources', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('customer_service', 'Customer Service'), ('legal', 'Legal'), ('facilities', 'Facilities'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('end_user', 'End User'), ('technician', 'Technician'), ('senior_technician', 'Senior Technician'), ('it_manager', 'IT Manager'), ('system_admin', 'System Administrator')], default='end_user', max_length=20),
        ),
    ]
