# Generated by Django 4.2.24 on 2025-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Assignment'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_user', 'Pending User Response'), ('pending_approval', 'Pending Approval'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
