# Generated by Django 4.2.24 on 2025-09-29 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Request Categories'},
        ),
        migrations.AddField(
            model_name='requestcategory',
            name='auto_assign_to_it',
            field=models.BooleanField(default=True, help_text='Automatically assign to IT department'),
        ),
        migrations.AddField(
            model_name='requestcategory',
            name='category_type',
            field=models.CharField(choices=[('hardware', 'Hardware Issues'), ('software', 'Software Issues'), ('network', 'Network & Connectivity'), ('access', 'Access & Permissions'), ('email', 'Email & Communication'), ('training', 'Training & Support'), ('maintenance', 'Maintenance & Updates'), ('security', 'Security Issues'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='requestcategory',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Requires manager approval'),
        ),
        migrations.AddField(
            model_name='requestcategory',
            name='sla_hours',
            field=models.IntegerField(default=24, help_text='Default SLA response time in hours'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='business_justification',
            field=models.TextField(blank=True, help_text='Business reason for this request'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='impact',
            field=models.CharField(choices=[('critical', 'Critical - System Down/Security Breach'), ('high', 'High - Major Impact on Operations'), ('medium', 'Medium - Standard Request'), ('low', 'Low - Enhancement/Non-urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='urgency',
            field=models.CharField(choices=[('critical', 'Critical - System Down/Security Breach'), ('high', 'High - Major Impact on Operations'), ('medium', 'Medium - Standard Request'), ('low', 'Low - Enhancement/Non-urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='channel',
            field=models.CharField(choices=[('web_portal', 'Web Portal'), ('mobile_app', 'Mobile App'), ('phone', 'Phone Call'), ('email', 'Email'), ('walk_in', 'Walk-in/In-Person'), ('chat', 'Live Chat'), ('self_service', 'Self-Service Portal')], default='web_portal', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical - System Down/Security Breach'), ('high', 'High - Major Impact on Operations'), ('medium', 'Medium - Standard Request'), ('low', 'Low - Enhancement/Non-urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_user', 'Pending User Response'), ('pending_approval', 'Pending Approval'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
